fixes #154: chore: deploy scripts should read private key from env var
farcasterxyz/contracts pull request #193
Opened 2023-03-03 02:40 UTC by appleseed-iii

## Motivation

Fix per #154

2023-03-05 05:09 UTC, varunsrin requested changes
Looks great! 

I had one small comment and you'll need to sign your commits before Github will allow a merge in this repo: https://github.com/farcasterxyz/hubble/blob/main/CONTRIBUTING.md#22-signing-commits

2023-03-05 05:09 UTC, varunsrin commented on script/BundleRegistry.s.sol
> +    address DEPLOYER = vm.addr(vm.envUint("PRIVATE_KEY"));
if these aren't compile time constants anymore, we should lower case them

2023-03-06 20:13 UTC, appleseed-iii commented
hey @varunsrin thanks. I force pushed my history to add the GPG signed commits. I also addressed your feedback in https://github.com/farcasterxyz/contracts/pull/193/commits/f36b4c2c5b3238c357549ad5625fb8003ff4b785

2023-03-06 20:48 UTC, varunsrin commented
thank you! whats your farcaster username?

2023-03-06 21:26 UTC, varunsrin approved these changes

2023-03-06 21:26 UTC, merged